# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bits < Formula
  desc "bits CLI — cryptocurrency data at your fingertips"
  homepage "https://github.com/mdnmdn/bits"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mdnmdn/bits/releases/download/v0.0.1/bits_0.0.1_darwin_amd64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"

      define_method(:install) do
        bin.install "bits"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mdnmdn/bits/releases/download/v0.0.1/bits_0.0.1_darwin_arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"

      define_method(:install) do
        bin.install "bits"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdnmdn/bits/releases/download/v0.0.1/bits_0.0.1_linux_amd64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
      define_method(:install) do
        bin.install "bits"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdnmdn/bits/releases/download/v0.0.1/bits_0.0.1_linux_arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
      define_method(:install) do
        bin.install "bits"
      end
    end
  end

  test do
    system "#{bin}/bits", "version"
  end
end
