# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bits < Formula
  desc "bits CLI — cryptocurrency data at your fingertips"
  homepage "https://github.com/mdnmdn/bits"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mdnmdn/bits/releases/download/v0.1.7/bits_0.1.7_darwin_amd64.tar.gz"
      sha256 "9e21145b9204204e52e005855d0573775c366f64fadb61fca87e13d1e3e582db"

      define_method(:install) do
        bin.install "bits"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mdnmdn/bits/releases/download/v0.1.7/bits_0.1.7_darwin_arm64.tar.gz"
      sha256 "d713771354782dd09721c583d809c3074895d86527d7f025bb88827298917758"

      define_method(:install) do
        bin.install "bits"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdnmdn/bits/releases/download/v0.1.7/bits_0.1.7_linux_amd64.tar.gz"
      sha256 "4ff7bd013b4aec53b9e7eb5fe772e892b08f43969c70b85694f9ac5501081ce0"
      define_method(:install) do
        bin.install "bits"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdnmdn/bits/releases/download/v0.1.7/bits_0.1.7_linux_arm64.tar.gz"
      sha256 "1c0b45324322cba1f218313bc70493bb2db91446188cf920adfb258ab656aa0a"
      define_method(:install) do
        bin.install "bits"
      end
    end
  end

  test do
    system "#{bin}/bits", "version"
  end
end
