# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bits < Formula
  desc "bits CLI — cryptocurrency data at your fingertips"
  homepage "https://github.com/mdnmdn/bits"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mdnmdn/bits/releases/download/v0.1.4/bits_0.1.4_darwin_amd64.tar.gz"
      sha256 "cd8c072bf51575a4f5204eed579906a5bc4de16de3be7f26673492efc1d11bd9"

      define_method(:install) do
        bin.install "bits"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mdnmdn/bits/releases/download/v0.1.4/bits_0.1.4_darwin_arm64.tar.gz"
      sha256 "39062d028f5fa006a7feafc218ea50c0e38df4d6463ae4cca012f057e8287166"

      define_method(:install) do
        bin.install "bits"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdnmdn/bits/releases/download/v0.1.4/bits_0.1.4_linux_amd64.tar.gz"
      sha256 "d57a3540e9ac5a59b23bb3c8e8e6c7c8fdf60b98ff2c4c85aceae075c7b61ced"
      define_method(:install) do
        bin.install "bits"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdnmdn/bits/releases/download/v0.1.4/bits_0.1.4_linux_arm64.tar.gz"
      sha256 "35b90614a87c5240b6cdcbdd578c0b242c210cb8e8e3c17a351490abbfca145d"
      define_method(:install) do
        bin.install "bits"
      end
    end
  end

  test do
    system "#{bin}/bits", "version"
  end
end
